# Generated by Django 3.2.12 on 2022-03-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shp',
            name='slug',
        ),
        migrations.AlterField(
            model_name='shp',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
